@startuml SimSimsDesign
left to right direction

/' Resources '/

class Worker {
    - __health: int
    + <<get, set>> health: int
    + is_dead(): bool
}

class Food {
    - __quality: int
    + <<get, set>> quality: int
}

class Product {
    
}

/' Locations '/    

class Barack {
    - __workers: queue<Worker>

    + add_worker(worker: Worker): void
    + take_worker(): Worker | None
}

class Barn {
    - __foods: queue<Food>

    + add_food(food: Food): void
    + take_food(): Food | None
}

class Storage {
    - __products: stack<Product>

    + add_product(product: Product): void
    + take_product(): Product | None
}

/' Transitions '/

class Transition {
    + transition(): void
    + has_resources(): bool
    + get_resources(): void
}

class Factory {
    - __channel_workers_in: Barack
    - __channel_workers_out: Barack
    - __channel_products_out: Storage

    - __workers: queue<Worker>
    - __risk: int
    + <<get, set>> risk: int
}

class FarmField {
    - __channel_workers_in: Barack
    - __channel_workers_out: Barack
    - __channel_foods_out: Barn

    - __workers: queue<Worker>
}

class FoodCourt {
    - __channel_workers_in: Barack
    - __channel_foods_in: Barn
    - __channel_workers_out: Barack

    - __workers: queue<Worker>
    - __foods: queue<Food>
}

class Home {
    - __channel_workers_in: Barack
    - __channel_products_in: Storage
    - __channel_workers_out: Barack

    - __workers: queue<Worker>
    - __products: queue<Product>

    - __reproduce: bool
    + update_reproduce(): void
}

Transition <- Factory
Transition <- FarmField
Transition <- FoodCourt
Transition <- Home

Factory *-- Barack
Factory *-- Storage
FarmField *-- Barack
FarmField *-- Barn
FoodCourt *-- Barack
FoodCourt *-- Barn
Home *-- Barack
Home *-- Storage

Barack *-- Worker
Barn *-- Food
Storage *-- Product

Factory *-- Worker
FarmField *-- Worker
FoodCourt *-- Worker
FoodCourt *-- Food
Home *-- Worker
Home *-- Product

@enduml
